# -*- coding: utf-8 -*-
"""Expert_Personal_Finance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hS3SroIYJrT-08O0YXAVRwoh4YDNM9jS

##variable intialization
"""

class finance_expert(object):
  Age = 0
  Income = 0
  Food = 0
  Rent = 0
  Health_insurance = 0
  Bills_utilities = 0 
  Transportation = 0
  Basic_clothes = 0
  Vacations = 0
  Trips= 0
  Expensive_clothes = 0
  Consumer_electronics = 0
  Dinig_out = 0
  Entertainment = 0
  Hobbies = 0
  Real_estate = 0
  Stocks = 0
  Mutalfunds = 0
  Pf_retirement = 0
  Fixed_deposit = 0
  age_finance_category=""
  income_category=""
  needs_total=0
  wants_total=0
  savings_total=0
  needs_per=0
  wants_per=0
  savings_per=0
  Food_per=0
  Rent_per=0
  Health_insurance_per=0
  Bills_utilities_per=0
  Transportation_per=0
  Basic_clothes_per=0
  Vacations_per=0
  Trips_per=0
  Expensive_clothes_per=0
  Consumer_electronics_per=0
  Dinig_out_per=0
  Entertainment_per=0
  Hobbies_per=0
  Real_estate_per=0
  Stocks_per=0
  Mutalfunds_per=0
  Pf_retirement_per=0
  Fixed_deposit_per=0
  needs_category=""
  wants_category=""
  savings_category=""
  Food_category=""
  Rent_category=""
  Health_insurance_category=""
  Bills_utilities_category=""
  Transportation_category=""
  Basic_clothes_category=""
  Vacations_category=""
  Trips_category=""
  Expensive_clothes_category=""
  Consumer_electronics_category=""
  Dinig_out_category=""
  Entertainment_category=""
  Hobbies_category=""
  Real_estate_category=""
  Stocks_category=""
  Mutalfunds_category=""
  Pf_retirement_category=""
  Fixed_deposit_category=""

  def __init__(self, age, income, food, rent, health_insurance, bills_utitlities, transportation, basic_clothes, vacations, trips, expensive_clothes, consumer_electronics, dinig_out, entertainment, hobbies, real_estate, stocks, mutual_funds, pf_retirement, fixed_deposite):
    finance_expert.Age = int(age)
    finance_expert.Income = int(income)
    finance_expert.Food = int(food)
    finance_expert.Rent = int(rent)
    finance_expert.Health_insurance = int(health_insurance)
    finance_expert.Bills_utilities = int(bills_utitlities)
    finance_expert.Transportation = int(transportation)
    finance_expert.Basic_clothes = int(basic_clothes)
    finance_expert.Vacations = int(vacations)
    finance_expert.Trips= int(trips)
    finance_expert.Expensive_clothes = int(expensive_clothes)
    finance_expert.Consumer_electronics = int(consumer_electronics)
    finance_expert.Dinig_out = int(dinig_out)
    finance_expert.Entertainment = int(entertainment)
    finance_expert.Hobbies = int(hobbies)
    finance_expert.Real_estate = int(real_estate)
    finance_expert.Stocks = int(stocks)
    finance_expert.Mutalfunds = int(mutual_funds)
    finance_expert.Pf_retirement = int(pf_retirement)
    finance_expert.Fixed_deposit = int(fixed_deposite)
    finance_expert.age_finance_category=""
    finance_expert.income_category=""
    finance_expert.needs_total=0
    finance_expert.wants_total=0
    finance_expert.savings_total=0
    finance_expert.needs_per=0
    finance_expert.wants_per=0
    finance_expert.savings_per=0
    finance_expert.Food_per=0
    finance_expert.Rent_per=0
    finance_expert.Health_insurance_per=0
    finance_expert.Bills_utilities_per=0
    finance_expert.Transportation_per=0
    finance_expert.Basic_clothes_per=0
    finance_expert.Vacations_per=0
    finance_expert.Trips_per=0
    finance_expert.Expensive_clothes_per=0
    finance_expert.Consumer_electronics_per=0
    finance_expert.Dinig_out_per=0
    finance_expert.Entertainment_per=0
    finance_expert.Hobbies_per=0
    finance_expert.Real_estate_per=0
    finance_expert.Stocks_per=0
    finance_expert.Mutalfunds_per=0
    finance_expert.Pf_retirement_per=0
    finance_expert.Fixed_deposit_per=0
    finance_expert.needs_category=""
    finance_expert.wants_category=""
    finance_expert.savings_category=""
    finance_expert.Food_category=""
    finance_expert.Rent_category=""
    finance_expert.Health_insurance_category=""
    finance_expert.Bills_utilities_category=""
    finance_expert.Transportation_category=""
    finance_expert.Basic_clothes_category=""
    finance_expert.Vacations_category=""
    finance_expert.Trips_category=""
    finance_expert.Expensive_clothes_category=""
    finance_expert.Consumer_electronics_category=""
    finance_expert.Dinig_out_category=""
    finance_expert.Entertainment_category=""
    finance_expert.Hobbies_category=""
    finance_expert.Real_estate_category=""
    finance_expert.Stocks_category=""
    finance_expert.Mutalfunds_category=""
    finance_expert.Pf_retirement_category=""
    finance_expert.Fixed_deposit_category=""

  def int_to_category(self):
    if finance_expert.Age <= 32:
      finance_expert.age_finance_category= "Junior"
    else:
      finance_expert.age_finance_category= "Senior"

    if finance_expert.Income<=2000:
      finance_expert.income_category ="lower_class"  
    elif finance_expert.Income>2000 and finance_expert.Income<=5500:
      finance_expert.income_category ="Middle_class" 
    else:
      finance_expert.income_category ="Upper_class"

    finance_expert.needs_total = finance_expert.Food+finance_expert.Rent+finance_expert.Health_insurance+finance_expert.Bills_utilities+finance_expert.Transportation+finance_expert.Basic_clothes
    finance_expert.wants_total = finance_expert.Vacations+finance_expert.Trips+finance_expert.Expensive_clothes+finance_expert.Consumer_electronics+finance_expert.Dinig_out+finance_expert.Entertainment+finance_expert.Hobbies
    finance_expert.savings_total = finance_expert.Real_estate+finance_expert.Stocks+finance_expert.Mutalfunds+finance_expert.Pf_retirement+finance_expert.Fixed_deposit

    finance_expert.needs_per=finance_expert.needs_total*100/finance_expert.Income
    finance_expert.wants_per=finance_expert.wants_total*100/finance_expert.Income
    finance_expert.savings_per=finance_expert.savings_total*100/finance_expert.Income

    finance_expert.Food_per = finance_expert.Food*100/finance_expert.needs_total
    finance_expert.Rent_per = finance_expert.Rent*100/finance_expert.needs_total
    finance_expert.Health_insurance_per = finance_expert.Health_insurance*100/finance_expert.needs_total
    finance_expert.Bills_utilities_per = finance_expert.Bills_utilities*100/finance_expert.needs_total
    finance_expert.Transportation_per = finance_expert.Transportation*100/finance_expert.needs_total
    finance_expert.Basic_clothes_per = finance_expert.Basic_clothes*100/finance_expert.needs_total

    finance_expert.Vacations_per=finance_expert.Vacations*100/finance_expert.wants_total
    finance_expert.Trips_per=finance_expert.Trips*100/finance_expert.wants_total
    finance_expert.Expensive_clothes_per=finance_expert.Expensive_clothes*100/finance_expert.wants_total
    finance_expert.Consumer_electronics_per=finance_expert.Consumer_electronics*100/finance_expert.wants_total
    finance_expert.Dinig_out_per=finance_expert.Dinig_out*100/finance_expert.wants_total
    finance_expert.Entertainment_per=finance_expert.Entertainment*100/finance_expert.wants_total
    finance_expert.Hobbies_per=finance_expert.Hobbies*100/finance_expert.wants_total

    finance_expert.Real_estate_per=finance_expert.Real_estate*100/finance_expert.savings_total 
    finance_expert.Stocks_per=finance_expert.Stocks*100/finance_expert.savings_total 
    finance_expert.Mutalfunds_per=finance_expert.Mutalfunds*100/finance_expert.savings_total 
    finance_expert.Pf_retirement_per=finance_expert.Pf_retirement*100/finance_expert.savings_total 
    finance_expert.Fixed_deposit_per=finance_expert.Fixed_deposit*100/finance_expert.savings_total 


    #--------------------Accumulated_finance_management_Section-----------------------------
    if finance_expert.age_finance_category=="Junior" :
      if finance_expert.needs_per>50:
        finance_expert.needs_category="redzone"
      else:
        finance_expert.needs_category="greenzone"  
      if finance_expert.wants_per>20:
        finance_expert.wants_category="redzone"
      else:
        finance_expert.wants_category="greenzone"
      if finance_expert.savings_per>30:
        finance_expert.savings_category="redzone"
      else:
        finance_expert.savings_category="greenzone"

    elif  finance_expert.age_finance_category=="Senior" :  
      if finance_expert.needs_per>40:
        finance_expert.needs_category="redzone"
      else:
        finance_expert.needs_category="greenzone"  
      if finance_expert.wants_per>20:
        finance_expert.wants_category="redzone"
      else:
        finance_expert.wants_category="greenzone"
      if finance_expert.savings_per>40:
        finance_expert.savings_category="redzone"
      else:
        finance_expert.savings_category="greenzone"  

    #---------------------NEEDS_Internal_Finance_Manage_section---------------------------------
    if finance_expert.Food_per>15:
      finance_expert.Food_category="redzone"
    else:
      finance_expert.Food_category="greenzone"  
    if finance_expert.Rent_per>35:
      finance_expert.Rent_category="redzone"
    else:
      finance_expert.Rent_category="greenzone"
    if finance_expert.Health_insurance_per>20:
      finance_expert.Health_insurance_category="redzone"
    else:
      finance_expert.Health_insurance_category="greenzone"
    if finance_expert.Bills_utilities_per>11:
      finance_expert.Bills_utilities_category="redzone"
    else:
      finance_expert.Bills_utilities_category="greenzone"  
    if finance_expert.Transportation_per>9:
      finance_expert.Transportation_category="redzone"
    else:
      finance_expert.Transportation_category="greenzone"
    if finance_expert.Basic_clothes_per>10:
      finance_expert.Basic_clothes_category="redzone"
    else:
      finance_expert.Basic_clothes_category="greenzone"

    #---------------------Wants_Internal_Finance_Manage_section---------------------------------

    if finance_expert.Vacations_per>13:
      finance_expert.Vacations_category="redzone"
    else:
      finance_expert.Vacations_category="greenzone"  
    if finance_expert.Trips_per>5:
      finance_expert.Trips_category="redzone"
    else:
      finance_expert.Trips_category="greenzone"
    if finance_expert.Expensive_clothes_per>10:
      finance_expert.Expensive_clothes_category="redzone"
    else:
      finance_expert.Expensive_clothes_category="greenzone"
    if finance_expert.Consumer_electronics_per>25:
      finance_expert.Consumer_electronics_category="redzone"
    else:
      finance_expert.Consumer_electronics_category="greenzone"  
    if finance_expert.Dinig_out_per>35:
      finance_expert.Dinig_out_category="redzone"
    else:
      finance_expert.Dinig_out_category="greenzone"
    if finance_expert.Entertainment_per>5:
      finance_expert.Entertainment_category="redzone"
    else:
      finance_expert.Entertainment_category="greenzone"  
    if finance_expert.Hobbies_per>7:
      finance_expert.Hobbies_category="redzone"
    else:
      finance_expert.Hobbies_category="greenzone"

    #---------------------Savings_Internal_Finance_Manage_section---------------------------------


    if finance_expert.Real_estate_per>10:
      finance_expert.Real_estate_category="redzone"
    else:
      finance_expert.Real_estate_category="greenzone"  
    if finance_expert.Stocks_per>5:
      finance_expert.Stocks_category="redzone"
    else:
      finance_expert.Stocks_category="greenzone"
    if finance_expert.Mutalfunds_per>9:
      finance_expert.Mutalfunds_category="redzone"
    else:
      finance_expert.Mutalfunds_category="greenzone"
    if finance_expert.Pf_retirement_per>40:
      finance_expert.Pf_retirement_category="redzone"
    else:
      finance_expert.Pf_retirement_category="greenzone"  
    if finance_expert.Fixed_deposit_per>36:
      finance_expert.Fixed_deposit_category="redzone"
    else:
      finance_expert.Fixed_deposit_category="greenzone"

"""## EXPERTA"""

from random import choice
from experta import *
import types

class ReturningEngine(KnowledgeEngine):
    def run(self, steps=float('inf'), generate=False):
        if not generate:
            to_return = list()
            for rhs in self._run_activations(steps=steps):
                res = rhs()
                if res is not None:
                    if isinstance(res, types.GeneratorType):
                        to_return.extend(res)
                    else:
                        return res
            return to_return
        else:
            def _run_as_generator():
                for rhs in self._run_activations(steps=steps):
                    res = rhs()
                    if res is not None:
                        if isinstance(res, types.GeneratorType):
                            yield from res
                        else:
                            return res
            return _run_as_generator()

    def _run_activations(self, steps=float('inf')):
        """
        Execute agenda activations
        """

        self.running = True
        activation = None
        execution = 0
        try:
            while steps > 0 and self.running:

                added, removed = self.get_activations()
                self.strategy.update_agenda(self.agenda, added, removed)

                if watchers.worth('AGENDA', 'DEBUG'):  # pragma: no cover
                    for idx, act in enumerate(self.agenda.activations):
                        watchers.AGENDA.debug(
                            "%d: %r %r",
                            idx,
                            act.rule.__name__,
                            ", ".join(str(f) for f in act.facts))

                activation = self.agenda.get_next()

                if activation is None:
                    break
                else:
                    steps -= 1
                    execution += 1

                    watchers.RULES.info(
                        "FIRE %s %s: %s",
                        execution,
                        activation.rule.__name__,
                        ", ".join(str(f) for f in activation.facts))

                    yield lambda: activation.rule(
                        self,
                        **{k: v
                           for k, v in activation.context.items()
                           if not k.startswith('__')})
        except:
            raise
        finally:
            self.running = False

class planselection(Fact):
  pass

class needcheck(Fact):
  pass
  
class wantcheck(Fact):
  pass

class savecheck(Fact):
  pass

class Incomebase(Fact):
  pass  
  
class Light(Fact):
  pass  

#Needs all check 
class Foodcheck(Fact):
  pass

class Rentcheck(Fact):
  pass

class Health_insurancecheck(Fact):
  pass

class Bills_utilitiescheck(Fact):
  pass

class Transportationcheck(Fact):
  pass

class Basic_clothescheck(Fact):
  pass

#Wants all check 
class Vacationscheck(Fact):
  pass

class Tripscheck(Fact):
  pass

class Expensive_clothescheck(Fact):
  pass

class Consumer_electronicscheck(Fact):
  pass

class Dinig_outcheck(Fact):
  pass

class Consumer_electronicscheck(Fact):
  pass

class Dinig_outcheck(Fact):
  pass

class Entertainmentcheck(Fact):
  pass

class Hobbiescheck(Fact):
  pass

#Savings and investment all check 
class Real_estatecheck(Fact):
  pass

class Stockscheck(Fact):
  pass

class Mutalfundscheck(Fact):
  pass

class Dinig_outcheck(Fact):
  pass

class Pf_retirementcheck(Fact):
  pass

class Fixed_depositcheck(Fact):
  pass


class personalfinancemanagement(ReturningEngine, finance_expert):
  
#--------------------------Plan Selection------------------------------  
  @Rule(planselection(age = "Junior"))
  def age_junior(self):
    print("---------------Welcome to personal finance management expert system-----------------")
    print("As per your age you come under 50-30-20 rule")
    yield ("---------------Welcome to personal finance management expert system-----------------","As per your age you come under 50-30-20 rule")
   
  @Rule(planselection(age = "Senior"))
  def age_senior(self):
    print("---------------Welcome to personal finance management expert system-----------------")
    print("As per your age you come under 40-20-40 rule")
    yield ("---------------Welcome to personal finance management expert system-----------------","As per your age you come under 40-20-40 rule")

#--------------------------Income base class------------------------------  
  @Rule(Incomebase(inclas = "lower_class" ))
  def income_lower(self):
    print("-As per your income invest in recurring ac and small period fixed deposits and take interest each smaller saving can give compound returns-")
    yield ("-As per your income invest in recurring ac and small period fixed deposits and take interest each smaller saving can give compound returns-")
   
  @Rule(Incomebase(inclas = 'Middle_class'))
  def income_middle(self):
    print("\n-As per your income invest in Share market and mutual funds and you are also advice to look into the term deposit-")
    yield ("\n-As per your income invest in Share market and mutual funds and you are also advice to look into the term deposit-")

  @Rule(Incomebase(inclas = 'Upper_class'))
  def income_upper(self):
    print("-As per your income invest in bigger investment bonds and in companies treasury bills-")  
    yield ("-As per your income invest in bigger investment bonds and in companies treasury bills-")  

#-------------------------------------------------------- 
  @Rule(needcheck(ncheck = "redzone" ))
  def ncheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of NEEDS is {}.which is violating  the rule".format(finance_expert.needs_per))
    yield ("-------Red Alert------","Your expenditure percentage of NEEDS is {}.which is violating  the rule".format(finance_expert.needs_per))

  @Rule(needcheck(ncheck = "greenzone" ))
  def ncheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of NEEDS is {} and it in the rule frame well done".format(finance_expert.needs_per))        
    yield ("-------Appreciation------", "Your expenditure percentage of NEEDS is {} and it in the rule frame well done".format(finance_expert.needs_per))
     
  @Rule(wantcheck(wcheck = "redzone" ))
  def wheck_red(self):     
    print("\n-------Red Alert------")
    print("Yor expenditure percentage of WANTS is {}.which is violating  the rule".format(finance_expert.wants_per))
    yield ("-------Red Alert------", "Yor expenditure percentage of WANTS is {}.which is violating  the rule".format(finance_expert.wants_per))

  @Rule(wantcheck(wcheck = "greenzone" ))
  def wcheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of WANTS is {} and it in the rule frame well done".format(finance_expert.wants_per))
    yield ("-------Appreciation------","Your expenditure percentage of WANTS is {} and it in the rule frame well done".format(finance_expert.wants_per))

  @Rule(savecheck(scheck = "redzone" ))
  def scheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Savings and Investment is {}.which is violating  the rule".format(finance_expert.savings_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Savings and Investment is {}.which is violating  the rule".format(finance_expert.savings_per))

  @Rule(savecheck(scheck = "greenzone" ))
  def scheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Savings and Investment is {} and it in the rule frame well done".format(finance_expert.savings_per))      
    yield ("-------Appreciation------","Your expenditure percentage of Savings and Investment is {} and it in the rule frame well done".format(finance_expert.savings_per))
    
  @Rule(Foodcheck(fcheck = "redzone" ))
  def fcheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of food is {}.which is violating  the rule".format(finance_expert.Food_per))
    yield ("-------Red Alert------", "Your expenditure percentage of food is {}.which is violating  the rule".format(finance_expert.Food_per))

  @Rule(Foodcheck(fcheck = "greenzone" ))
  def fcheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of food is {} and it in the rule frame well done".format(finance_expert.Food_per))
    yield ("-------Appreciation------", "Your expenditure percentage of food is {} and it in the rule frame well done".format(finance_expert.Food_per))

  @Rule(Rentcheck(rcheck = "redzone" ))
  def rcheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Rent is {}.which is violating  the rule".format(finance_expert.Rent_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Rent is {}.which is violating  the rule".format(finance_expert.Rent_per))

  @Rule(Rentcheck(rcheck = "greenzone" ))
  def rcheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Rent is {} and it in the rule frame well done".format(finance_expert.Rent_per))
    yield ("-------Appreciation------", "Your expenditure percentage of Rent is {} and it in the rule frame well done".format(finance_expert.Rent_per))

  @Rule(Health_insurancecheck(hcheck = "redzone" ))
  def hcheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Health insurance is {}.which is violating  the rule".format(finance_expert.Health_insurance_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Health insurance is {}.which is violating  the rule".format(finance_expert.Health_insurance_per))

  @Rule(Health_insurancecheck(hcheck = "greenzone" ))
  def hcheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Health insurance is {} and it in the rule frame well done".format(finance_expert.Health_insurance_per))  
    yield ("-------Appreciation------","Your expenditure percentage of Health insurance is {} and it in the rule frame well done".format(finance_expert.Health_insurance_per))
     
  @Rule(Bills_utilitiescheck(bcheck = "redzone" ))
  def bcheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Bills utilities is {}.which is violating  the rule".format(finance_expert.Bills_utilities_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Bills utilities is {}.which is violating  the rule".format(finance_expert.Bills_utilities_per))

  @Rule(Bills_utilitiescheck(bcheck = "greenzone" ))
  def bcheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Bills utilities is {} and it in the rule frame well done".format(finance_expert.Bills_utilities_per))  
    yield ("-------Appreciation------", "Your expenditure percentage of Bills utilities is {} and it in the rule frame well done".format(finance_expert.Bills_utilities_per))

  @Rule(Transportationcheck(tcheck = "redzone" ))
  def tchek_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Transportation is {}.which is violating  the rule".format(finance_expert.Transportation_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Transportation is {}.which is violating  the rule".format(finance_expert.Transportation_per))

  @Rule(Transportationcheck(tcheck = "greenzone" ))
  def tchek_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Transportation is {} and it in the rule frame well done".format(finance_expert.Transportation_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Transportation is {} and it in the rule frame well done".format(finance_expert.Transportation_per))

  @Rule(Basic_clothescheck(bccheck = "redzone" ))
  def bccheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Basic clothes is {}.which is violating  the rule".format(finance_expert.Basic_clothes_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Basic clothes is {}.which is violating  the rule".format(finance_expert.Basic_clothes_per))

  @Rule(Basic_clothescheck(bccheck = "greenzone" ))
  def bccheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Basic clothes is {} and it in the rule frame well done".format(finance_expert.Basic_clothes_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Basic clothes is {} and it in the rule frame well done".format(finance_expert.Basic_clothes_per))

######Wants Internal  
       
  @Rule(Vacationscheck(vaccheck = "redzone" ))
  def vaccheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Vacations is {}.which is violating  the rule".format(finance_expert.Vacations_per))
    yield ("-------Red Alert------","Your expenditure percentage of Vacations is {}.which is violating  the rule".format(finance_expert.Vacations_per) )

  @Rule(Vacationscheck(vaccheck = "greenzone" ))
  def vaccheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Vacations is {} and it in the rule frame well done".format(finance_expert.Vacations_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Vacations is {} and it in the rule frame well done".format(finance_expert.Vacations_per))
        
  @Rule(Tripscheck(tripcheck = "redzone" ))
  def tripcheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Trips is {}.which is violating  the rule".format(finance_expert.Trips_per))
    yield ("\n-------Red Alert------", "Your expenditure percentage of Trips is {}.which is violating  the rule".format(finance_expert.Trips_per))

  @Rule(Tripscheck(tripcheck = "greenzone" ))
  def tripcheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Trips is {} and it in the rule frame well done".format(finance_expert.Trips_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Trips is {} and it in the rule frame well done".format(finance_expert.Trips_per))
        
  @Rule(Expensive_clothescheck(expccheck = "redzone" ))
  def expccheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Expensive clothes is {}.which is violating  the rule".format(finance_expert.Expensive_clothes_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Expensive clothes is {}.which is violating  the rule".format(finance_expert.Expensive_clothes_per))

  @Rule(Expensive_clothescheck(expccheck = "greenzone" ))
  def expccheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Expensive clothes is {} and it in the rule frame well done".format(finance_expert.Expensive_clothes_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Expensive clothes is {} and it in the rule frame well done".format(finance_expert.Expensive_clothes_per))
             
  @Rule(Consumer_electronicscheck(conecheck = "redzone" ))
  def conecheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Consumer electronics is {}.which is violating  the rule".format(finance_expert.Consumer_electronics_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Consumer electronics is {}.which is violating  the rule".format(finance_expert.Consumer_electronics_per))

  @Rule(Consumer_electronicscheck(conecheck = "greenzone" ))
  def conecheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Consumer electronics is {} and it in the rule frame well done".format(finance_expert.Consumer_electronics_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Consumer electronics is {} and it in the rule frame well done".format(finance_expert.Consumer_electronics_per))

  @Rule(Dinig_outcheck(dincheck = "redzone" ))
  def dincheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Dinig out is {}.which is violating  the rule".format(finance_expert.Dinig_out_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Dinig out is {}.which is violating  the rule".format(finance_expert.Dinig_out_per))

  @Rule(Dinig_outcheck(dincheck = "greenzone" ))
  def dincheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Dinig out is {} and it in the rule frame well done".format(finance_expert.Dinig_out_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Dinig out is {} and it in the rule frame well done".format(finance_expert.Dinig_out_per))
       
  @Rule(Entertainmentcheck(entcheck = "redzone" ))
  def entcheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Entertainment is {}.which is violating  the rule".format(finance_expert.Entertainment_per))
    yield ("\n-------Red Alert------", "Your expenditure percentage of Entertainment is {}.which is violating  the rule".format(finance_expert.Entertainment_per))

  @Rule(Entertainmentcheck(entcheck = "greenzone" ))
  def entcheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Entertainment is {} and it in the rule frame well done".format(finance_expert.Entertainment_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Entertainment is {} and it in the rule frame well done".format(finance_expert.Entertainment_per))

  @Rule(Hobbiescheck(hobcheck = "redzone" ))
  def hobcheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Hobbies is {}.which is violating  the rule".format(finance_expert.Hobbies_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Hobbies is {}.which is violating  the rule".format(finance_expert.Hobbies_per))

  @Rule(Hobbiescheck(hobcheck = "greenzone" ))
  def hobcheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Hobbies is {} and it in the rule frame well done".format(finance_expert.Hobbies_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Hobbies is {} and it in the rule frame well done".format(finance_expert.Hobbies_per))

######Savings And investment Internal

  @Rule(Real_estatecheck(realcheck = "redzone" ))
  def realcheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Real estate is {}.which is violating  the rule".format(finance_expert.Real_estate_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Real estate is {}.which is violating  the rule".format(finance_expert.Real_estate_per))

  @Rule(Real_estatecheck(realcheck = "greenzone" ))
  def realcheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Real estate is {} and it in the rule frame well done".format(finance_expert.Real_estate_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Real estate is {} and it in the rule frame well done".format(finance_expert.Real_estate_per))

  @Rule(Stockscheck(stoccheck = "redzone" ))
  def stoccheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Stocks is {}.which is violating  the rule".format(finance_expert.Stocks_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Stocks is {}.which is violating  the rule".format(finance_expert.Stocks_per))

  @Rule(Stockscheck(stoccheck = "greenzone" ))
  def stoccheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Stocks is {} and it in the rule frame well done".format(finance_expert.Stocks_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Stocks is {} and it in the rule frame well done".format(finance_expert.Stocks_per))

  @Rule(Mutalfundscheck(mulcheck = "redzone" ))
  def mulcheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Mutalfunds is {}.which is violating  the rule".format(finance_expert.Mutalfunds_per))
    yield ("\n-------Red Alert------", "Your expenditure percentage of Mutalfunds is {}.which is violating  the rule".format(finance_expert.Mutalfunds_per))

  @Rule(Mutalfundscheck(mulcheck = "greenzone" ))
  def mulcheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Mutalfunds is {} and it in the rule frame well done".format(finance_expert.Mutalfunds_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Mutalfunds is {} and it in the rule frame well done".format(finance_expert.Mutalfunds_per))

  @Rule(Pf_retirementcheck(pfrcheck = "redzone" ))
  def pfrcheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Pf_retirement is {}.which is violating  the rule".format(finance_expert.Pf_retirement_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Pf_retirement is {}.which is violating  the rule".format(finance_expert.Pf_retirement_per))

  @Rule(Pf_retirementcheck(pfrcheck = "greenzone" ))
  def pfrcheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Pf_retirement is {} and it in the rule frame well done".format(finance_expert.Pf_retirement_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Pf_retirement is {} and it in the rule frame well done".format(finance_expert.Pf_retirement_per))

  @Rule(Fixed_depositcheck(fdcheck = "redzone" ))
  def fdcheck_red(self):     
    print("\n-------Red Alert------")
    print("Your expenditure percentage of Fixed deposit is {}.which is violating  the rule".format(finance_expert.Fixed_deposit_per))
    yield ("-------Red Alert------", "Your expenditure percentage of Fixed deposit is {}.which is violating  the rule".format(finance_expert.Fixed_deposit_per))

  @Rule(Fixed_depositcheck(fdcheck = "greenzone" ))
  def fdcheck_green(self):
    print("")
    print("-------Appreciation------")
    print("Your expenditure percentage of Fixed deposit is {} and it in the rule frame well done".format(finance_expert.Fixed_deposit_per)) 
    yield ("-------Appreciation------", "Your expenditure percentage of Fixed deposit is {} and it in the rule frame well done".format(finance_expert.Fixed_deposit_per))
